productSample = [
    "Tôi muốn mua bánh STRAWBERRY CHEDDARS cho sinh nhật, bạn có thể cho thêm thông tin không?",
    "Bánh nào phù hợp để tặng bạn bè nhân dịp lễ kỷ niệm?",
    "Tôi muốn đặt một hộp CHEESE LOVER cho buổi tiệc, bạn có còn hàng không?",
    "Có loại bánh nào cho tiệc cưới không?",
    "Bạn có gợi ý bánh nào thích hợp để tặng mẹ vào dịp sinh nhật không?",
    "Tôi muốn đặt bánh MANGO DELUXE cho ngày lễ tình nhân, bạn có thể cho thêm thông tin không?",
    "Có bánh gì phù hợp để biếu trong dịp lễ tết không?",
    "Bánh nào là best-seller tại cửa hàng của bạn?",
    "Tôi muốn mua bánh BLUEBERRY ANGEL để chúc mừng tốt nghiệp, bạn có gợi ý thêm không?",
    "Bạn có thể gợi ý một set bánh nhỏ phù hợp để tặng người yêu không?",
    "Bánh nào phù hợp để tặng vào ngày Phụ nữ Việt Nam?",
    "Tôi muốn đặt một bánh sinh nhật EVENT CAKE cho buổi tiệc khai trương.",
    "Bạn có loại bánh nào có topping phô mai không?",
    "Tôi cần đặt một set MINI DORAEMON cho lễ kỷ niệm tình yêu, bạn có còn hàng không?",
    "Bạn có loại bánh nào phù hợp cho dịp Tết không?",
    "Có set bánh nào đặc biệt cho các bé không?",
    "Tôi muốn mua bánh ALMOND CHOCOLATE CRUNCH để tặng ông bà nhân dịp Tết.",
    "Bạn có thể làm một set bánh với phong cách cổ điển không?",
    "Tôi cần bánh để trang trí bàn tiệc, bạn có loại nào phù hợp không?",
    "Bạn có loại bánh nào phù hợp làm quà tặng cho đồng nghiệp không?",
    "Bánh nào đẹp để tặng vợ nhân kỷ niệm ngày cưới?",
    "Tôi cần đặt bánh EVENT CAKE S02 cho một sự kiện lớn.",
    "Bạn có thể gợi ý bánh nào phù hợp để tặng người thân ở bệnh viện không?",
    "Tôi muốn mua một set MINI LUXURY để tặng ông bà nhân dịp lễ Tết.",
    "Có bánh gì đơn giản để tặng bạn nhân dịp sinh nhật không?",
    "Bánh nào phù hợp để chúc mừng bạn mới sinh con?",
    "Tôi muốn đặt bánh nhân dịp công ty kỷ niệm 50 năm thành lập, có loại nào phù hợp không?",
    "Bạn có thể làm một bánh đặc biệt với màu sắc và hương vị theo yêu cầu không?",
    "Tôi muốn mua bánh SET MINI VANILLA để tặng người lớn tuổi.",
    "Có bánh nào phù hợp để tặng vào dịp Phật Đản không?"
]


chitchatSample = [
    "Xin chao",
    "Hi",
    "Hello",
    "Chào bạn",
    "Hello shop",
    "Chàp shop",
    "Chào bạn! Hôm nay bạn thế nào?",
    "Bạn có thể kể cho tôi nghe về ngày hôm nay của bạn không?",
    "Bạn có thể giúp tôi thư giãn một chút được không?",
    "Bạn thích thời tiết như thế nào?",
    "Bạn làm việc ở đây bao lâu rồi?",
    "Bạn có thích nói chuyện với khách hàng không?",
    "Có điều gì thú vị bạn muốn chia sẻ không?",
    "Bạn có thể kể về lịch sử của cửa hàng không?",
    "Bạn nghĩ gì về mùa xuân?",
    "Bạn có lời khuyên nào để có một ngày vui vẻ không?",
    "Bạn có thể kể một câu chuyện vui không?",
    "Bạn thích làm gì vào thời gian rảnh?",
    "Bạn có biết món ăn nào ngon gần đây không?",
    "Bạn có sở thích nào đặc biệt không?",
    "Bạn có tin vào may mắn không?",
    "Bạn có thể dạy tôi cách chăm sóc hoa không?",
    "Công việc ở cửa hàng này có thú vị không?",
    "Bạn có gặp khách hàng thú vị nào không?",
    "Bạn thích làm việc một mình hay cùng đồng nghiệp?",
    "Bạn có thể chia sẻ một bí quyết thành công trong cuộc sống không?",
    "Bạn có thói quen nào đặc biệt vào buổi sáng không?",
    "Bạn có thể kể về một kỷ niệm đẹp khi làm việc ở đây không?",
    "Bạn nghĩ gì về việc chăm sóc cây cảnh?",
    "Bạn có thể đề xuất một quyển sách hay để đọc không?",
    "Bạn có thể kể về một khách hàng dễ thương mà bạn đã gặp không?",
    "Bạn có tin vào ý nghĩa của các loài hoa không?",
    "Bạn có thể giúp tôi chọn hoa cho một dịp đặc biệt không?"
]
